### PR TITLE
Use Typescript as default

### PR DESCRIPTION
**Pull request by BasixKOR**

### CODE REVIEW

**Comment by BasixKOR** [comment]
Sorry, it was inteded to be a pull request for my own repo.

**Comment by abhijithvijayan** [comment]
its a lot to review.

Could you list out what all is implemented.

And why was wext-manifest package replaced.

**Comment by BasixKOR** [comment]
I've mistaken my own repo and this repo. Could you remove this PR if you can?

**Comment by abhijithvijayan** [comment]
Its fine.

I am not gonna merge it.

**Pull request closed without merging**
